"Start of the vim-plug manager
call plug#begin()
	
		Plug 'scrooloose/nerdtree'
		Plug 'flazz/vim-colorschemes'
		Plug 'valloric/youcompleteme'
		Plug 'nathanaelkane/vim-indent-guides'

call plug#end()
"End vim-plug manager


set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab

syntax on
highlight linenr ctermfg=green

colorscheme asmdev

"Colors for autocompletetion
highlight Pmenu ctermfg=9 ctermbg=0

set number

filetype plugin indent on

autocmd FileType python map <F5> :w !python3 <CR>
autocmd FileType javascript map  <F5> :w !node <CR>
autocmd FileType sh map <F5> :w !bash <CR>
autocmd FileType tex map  <F5> :w !pdflatex % <CR>
